# Generated by Django 5.1.4 on 2025-02-03 04:07

import facturacion.validadores
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpassword',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[facturacion.validadores.Validacion_letras]),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, validators=[facturacion.validadores.Validacion_letras]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=30, validators=[facturacion.validadores.Validacion_letras]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[facturacion.validadores.validacion_numeros]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=30, validators=[facturacion.validadores.Validacion_letras]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[facturacion.validadores.validacion_numeros]),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=200, validators=[facturacion.validadores.Validacion_letras]),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ruc',
            field=models.CharField(max_length=13, primary_key=True, serialize=False, validators=[facturacion.validadores.validacion_numeros]),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[facturacion.validadores.validacion_numeros]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[facturacion.validadores.validacion_numeros]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100, validators=[facturacion.validadores.Validacion_letras]),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=200, validators=[facturacion.validadores.Validacion_letras]),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='ruc',
            field=models.CharField(max_length=13, primary_key=True, serialize=False, validators=[facturacion.validadores.validacion_numeros]),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[facturacion.validadores.validacion_numeros]),
        ),
    ]
